
  - name: Check if nix is installed
    ansible.builtin.shell: nix-build --version
    become_user: marco
    args:
      executable: /bin/bash
    register: nix_check
    ignore_errors: true

  - name: Install baseline packages
    ansible.builtin.apt:
      name: xz-utils
      update_cache: yes
    become_user: marco

  - name: Download nix install file
    ansible.builtin.get_url:
      url: https://releases.nixos.org/nix/nix-2.24.5/install
      dest: /tmp/install_nix.sh
      checksum: sha256:10aa09252316c35092ffe2f90093da463147b220543fabb88ec02bee9619d3bb
    become_user: marco
    when: nix_check is failed

  - name: Install nix
    ansible.builtin.command: sh /tmp/install_nix.sh --daemon --yes
    become_user: marco
    when: nix_check is failed

  - name: Update nix packages
    ansible.builtin.shell: nix-channel --update
    become_user: marco
    args:
      executable: /bin/bash
    when: nix_check is failed

  - name: Enable nix flakes
    ansible.builtin.lineinfile:
      path: /etc/nix/nix.conf
      line: experimental-features = nix-command flakes
