
- name: Create wheel group
  group:
    name: wheel
    state: present

- name: Create user
  ansible.builtin.user:
    name: marco
    password: "{{ secrets.marco_password }}"
    shell: /bin/bash
    groups: wheel
    create_home: yes

- name: Install utils packages
  ansible.builtin.apt:
    pkg:
      - git
      - neovim
    state: latest
    update_cache: true
  become_user: marco
