- name: Check Minikube's status.
  command: minikube status
  register: minikube_status
  changed_when: false
  ignore_errors: true
  become_user: marco

- name: Start Minikube if it's not running.
  command: minikube start
  become: yes
  become_user: marco
  when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
